from typing import Protocol
from uuid import UUID

from src.domain.entities.user import User, UserProfile


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...

    async def get_by_telegram_id(self, telegram_id: int) -> User | None: ...

    async def create(self, user: User) -> User: ...

    async def update(self, user: User) -> User: ...

    async def get_profile(self, user_id: UUID) -> UserProfile | None: ...

    async def upsert_profile(self, profile: UserProfile) -> UserProfile: ...
